openapi: 3.0.0
info:
  title: Translator API
  description: API for translating text using Google Translate
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /:
    get:
      summary: Test endpoint
      description: test endpoint
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true

  /translate:
    post:
      summary: Translate text
      description: Translate text from source language to target language
      parameters:
        - in: query
          name: text
          schema:
            type: string
            example: testo da tradurre
          required: true
          description: The text to translate
        - in: query
          name: source
          schema:
            type: string
            example: it
          required: false
          description: The source language code (e.g., en, es, fr)
        - in: query
          name: target
          schema:
            type: string
            example: en
          required: true
          description: The target language code (e.g., en, es, fr)
      responses:
        '200':
          description: Translation successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                    example: true
                    description: always true is success
                  translations:
                    type: array
                    description: The translated text
                    items:
                      type: object
                      properties:
                        lang:
                          type: string
                          description: The language code of the translation
                          example: en
                        translatedText:
                          type: string
                          description: The translated text
                          example: HI
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message

