openapi: 3.0.0
info:
  title: Translator API
  description: API for translating text using Google Translate
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /translate:
    post:
      summary: Translate text
      description: Translate text from source language to target language
      parameters:
        - in: query
          name: text
          schema:
            type: string
          required: true
          description: The text to translate
        - in: query
          name: source
          schema:
            type: string
          required: true
          description: The source language code (e.g., en, es, fr)
        - in: query
          name: target
          schema:
            type: string
          required: true
          description: The target language code (e.g., en, es, fr)
      responses:
        '200':
          description: Translation successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  translatedText:
                    type: string
                    description: The translated text
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
